name: pokedex
description: "Pokédex utilizando PokeAPI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  http: ^1.2.1
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.2.3
  signals: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/icons/'
